### ISSUE TITLE
idm-admin shows errors `Could not load EntryPoint.parse`

### ISSUE THREAD

**Issue by drasko** [ging/fiware-idm-deprecated#60]
``` bash
drasko@Lenin:~/mainflux/fiware-idm$ idm-admin --help
usage: idm-admin [--version] [-v] [--log-file LOG_FILE] [-q] [-h] [--debug]

Some tools to help with common tasks using FIWARE IdM Keyrock

optional arguments:
  --version            show program's version number and exit
  -v, --verbose        Increase verbosity of output. Can be repeated.
  --log-file LOG_FILE  Specify a file to log output. Disabled by default.
  -q, --quiet          Suppress output except warnings and errors.
  -h, --help           Show help message and exit.
  --debug              Show tracebacks on errors.

Commands:
Could not load EntryPoint.parse('cancel-accounts = tools.keystone:CancelAccounts')
  complete       print bash completion command
Could not load EntryPoint.parse('console = tools.keystone:Console')
Could not load EntryPoint.parse('create-endpoints = tools.keystone:CreateNewEndpoints')
Could not load EntryPoint.parse('delete-region = tools.keystone:DeleteRegionAndEndpoints')
  help           print detailed help for another command
Could not load EntryPoint.parse('tweak-database = tools.keystone:DatabaseTweak')
drasko@Lenin:~/mainflux/fiware-idm$ 
```

**Comment by federicofdez** [comment]
Hi @drasko,

Thanks for writing. As you may have noticed, this issue wouldn't prevent any of the commands from running (you could try, for instance, `idm-admin console` and you would find no trouble at all). Anyway, I just took a look into it, and there seemed to be an issue when installing the dependencies of `idm-admin` package, caused by a change to our Python Keystoneclient egg name we recently made.

I fixed this in ec17455fc2fa471102b4f701ad19e6141b55b052, so you only need to install the admin tools again, by running the following:

```
$ sudo pip install -r requirements.txt
$ sudo python setup.py install
```

Shouldn't this solve your issue, just come back to us again and provide the stack trace you get when running `idm-admin --debug --help`.

Best regards,
Federico Fernández

**Comment by federicofdez** [comment]
Seems to be solved. Feel free to reopen the issue if the problem persists.

Cheers!

**Comment by pfazenda** [comment]
Still not solved. I just cloned the latest version and I am still having the same problem...
